### PR TITLE
React to `HtmlString` removal from Mvc.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
https://github.com/aspnet/Mvc/issues/4558

Associated PR: https://github.com/aspnet/Mvc/pull/4651

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
Note: The breaking change is in for `HtmlAbstractions`.

**Comment by laskoviymishka** [comment]
@NTaylorMullen this PR is not correct, prime cache helper require both:
```
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc.Rendering;
```

One for `HtmlString`, another one for `IHtmlHelper` (it still in `namespace Microsoft.AspNetCore.Mvc.Rendering` [you can check here](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/IHtmlHelper.cs) ).

**Comment by NTaylorMullen** [comment]
:up: :date:

**Comment by laskoviymishka** [comment]
:up:

**Comment by laskoviymishka** [comment]
@SteveSandersonMS this PR is obsolete now, i accidently fix this issue with _https://github.com/aspnet/JavaScriptServices/pull/88/files#diff-f2b00f5837f8ffaf55aa82f56f176132R6_
@NTaylorMullen sorry for this :sob:

**Comment by NTaylorMullen** [comment]
@laskoviymishka all good!

**Pull request closed without merging**
