### PR TITLE
net451 support and netcoreapp1.0->netstandard1.5 for libraries

### PR DESCRIPTION
**Pull request by rmja**
Resolves https://github.com/aspnet/JavaScriptServices/issues/89

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks very much! This is now merged.

If you discover anything not working on .NET 4.5.1, please let me know. My testing has been all about .NET Core.

**Comment by zigzag95** [comment]
Thank you
Nuget ready?

**Comment by laskoviymishka** [comment]
What about netsyandart 1.6? It's escalate quickly :)

**Comment by xabikos** [comment]
Actually instead of targeting netstandard1.6 we should try and target a lowest number if possible (1.3) as this would give much more compatibility especially now that full .net framework is supported. Of course I don't know if it's possible based on api's the library uses.

**Comment by laskoviymishka** [comment]
Well it could, we need investigate possibilities of such targeting's

**Pull request closed without merging**
