### PR TITLE
Bug(KnockoutSpa): Router TS issue

### PR DESCRIPTION
**Pull request by MarkPieszak**
TS erroring out (unable to build) due to `crossroads.normalizeFn = crossroads.NORM_AS_OBJECT;` <-- left hand assignment

```
ERROR in ./ClientApp/router.ts
(21,9): error TS2450: Left-hand side of assignment expression cannot be a constant 
or a read-only property.
```

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

I'm not following why TypeScript 2 is reporting that error. Is it a bug in TypeScript 2? Why does it think the LHS of the assignment is a constant?

If we do need to work around it, could we do so in a more targeted way that doesn't discard all type information for the `crossroads` package?

**Comment by MarkPieszak** [comment]
It looks like changing this to `import crossroads = require('crossroads');` is the best bet, I meant to change it to that, apologies! That way we keep the intellisense.

Let me look into this more and see why it's creeping up now in the first place, I'll get back to you!

**Comment by SteveSandersonMS** [comment]
Thanks. Looks like the reason is as discussed here: http://stackoverflow.com/questions/38818475/left-hand-side-of-assignment-expression-cannot-be-a-constant-or-a-read-only-prop

**Comment by SteveSandersonMS** [comment]
Merged

**Comment by MarkPieszak** [comment]
Since you were wondering as well, found out why this was creeping up now with 2.0. Apparently it was a TS bug because it *wasn't* showing up. This was fixed in 2.0.

http://stackoverflow.com/questions/38818475/left-hand-side-of-assignment-expression-cannot-be-a-constant-or-a-read-only-prop

This is because in es6 all module's variables are considered constants.

https://github.com/Microsoft/TypeScript/issues/6751#issuecomment-177114001
In TypeScript 2.0 the bug (of not reporting this error) was fixed.

Another workaround is that we could do `(crossroads as any).normalizeFn` ? Interesting.

> Since mongoose is still using the commonjs - var mongoose = require("mongoose") - not the es6 import syntax (which is used in the typings), you can suppress the error by assuming the module is of type any.
> 
> WORKAROUND:
> 
> (mongoose as any).Promise = global.Promise;

**Pull request closed without merging**
