### PR TITLE
Updating aspnet-webpack-react to work with react-hot-loader v4

### PR DESCRIPTION
**Pull request by tjaskula**
This should solve the issue #1585 

- Deleting references to `react-hot-loader/webpack` and `react-hot-loader/patch` as it was removed in v4 of react-hot-loader. Referencing `react-hot-loader/babel`in webpack configuration is enough.
- Bumping peer dependency of webpack to 3 and 4

### CODE REVIEW

**Comment by natemcmaster** [comment]
Thanks for taking a look @SteveSandersonMS. 

Side note: I was playing around with this over the weekend at seemed to me like improvements to react-hot-loader and webpack 4 make aspnet-webpack-react unnecessary. I got hmr working just fine without it. I'm not proposing anything...just pointing out that I couldn't figure out what aspnet-webpack-react was supposed to do.

**Comment by SteveSandersonMS** [comment]
@natemcmaster Were you using the SPA templates from ASP.NET Core 2.0 or later? If so, you're not using `aspnet-webpack-react` at all. It's only used by pre-2.0 templates.

**Comment by natemcmaster** [comment]
I see, makes sense. I was setting up hmr with ASP.NET Core 2.1 on an old hobby project I was upgrading from ASP.NET 4. I didn't see HMR in the latest SPA templates so wasn't sure what to do.

**Comment by tjaskula** [comment]
@SteveSandersonMS Thanks for suggestions. I'll target Webpack 4 only which will be related to the changes.
@natemcmaster You mean you made working HMR and ASP.NET core (on kestrel) without this module? I don't remeber now but it seems that enabling HMR yielded an error thus this PR.

**Comment by natemcmaster** [comment]
> You mean you made working HMR and ASP.NET core (on kestrel) without this module?

@tjaskula yes. It may require updating to the latest versions of webpack and react-hot-loader, but I got it working just fine without aspnet-webpack-react. I wrote up a quick demo and post about this https://natemcmaster.com/blog/2018/07/05/aspnetcore-hmr/

**Comment by tjaskula** [comment]
@natemcmaster I checked what was different in my configuration and realized that in ASP.NET Core I had this configuration:

```
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
{
     HotModuleReplacement = true,
     ReactHotModuleReplacement = true,
     ProjectPath = System.IO.Path.Combine(env.ContentRootPath, "../")
});
```

Notice the flag `ReactHotModuleReplacement = true`. When this is set, the `aspnet-webpack-react` dependency is loaded with an error described in the issue #1585.

When I comment out `ReactHotModuleReplacement` the error goes away (I'm also using ASP.NET Core 2.1)

My point is that, if you're using ASP.NET Core 2.1, just go without `aspnet-webpack-react` and `ReactHotModuleReplacement` flag. (as @SteveSandersonMS mentioned it above)

For ASP.NET Core < 2.0 this PR might be of value.

I'm making changes to the PR as requested above.

**Comment by cvanem** [comment]
@tjaskula Thanks for clearing this up.  Removing aspnet-webpack-react and REactHotMudleReplacement = true resolved my error and HMR still functions as expected.

**Comment by tjaskula** [comment]
@natemcmaster do sourcemaps works for you ? I noticed that for me it doesn't load properly in Chrome

**Comment by natemcmaster** [comment]
Yeah, I got those working with the inline-source-map devtool and awesome-typescript-loader.

**Comment by tjaskula** [comment]
All is ok, I was using webpack.SourceMapdevtoolPlugin which seems broken. Swtiching to detool: inline-source-map seems fixing the issue.

**Comment by tjaskula** [comment]
I've pushed the required changes. Please review if this is ok.

**Comment by Tsourdox** [comment]
Really need this one. What's the eta for reviewing this PR?

**Comment by Eilon** [comment]
@SteveSandersonMS ?

**Comment by SteveSandersonMS** [comment]
Thanks for the prompt. This is now merged and published as `aspnet-webpack-react@4.0.0`.

**Pull request closed without merging**
