### PR TITLE
Added support for Thenables

### PR DESCRIPTION
**Pull request by waterfoul**

### CODE REVIEW

**Comment by waterfoul** [comment]
@natemcmaster Does anyone look at PRs in the project?

**Comment by natemcmaster** [comment]
Paging @SteveSandersonMS @Eilon.

@waterfoul I don't have enough context on this piece of code to know if this is something we want, sorry.

**Comment by waterfoul** [comment]
@natemcmaster Any suggestions on getting this some attention? It brings the webpack support up to snuff with the documentation and we are having to resort to including a .tar file in all of our projects in order to use the patched code.

**Comment by natemcmaster** [comment]
I'll use my internal email powers to ping the right people again.

**Comment by SteveSandersonMS** [comment]
Thanks for contributing this! It's now merged (with some stylistic tweaks - hope you don't mind).

**Pull request closed without merging**
