### PR TITLE
Updated all template project.json tools to use 1.1

### PR DESCRIPTION
**Pull request by Gimly**
I figured out what was causing the issue that I had opened in #534. It was not really linked to Angular or anything as the error message could suggest, but to the publishing process.

I'm publishing my app through Bitbucket Pipelines that runs  a script in a Docker image to create a CI/CD system. The script I was using was simply running `dotnet restore` and then `dotnet publish`. What I hadn't seen was that `dotnet publish-iis` that is called by the post publish methods was failing. It was failing because on the docker image I'm using (microsoft/aspnetcore-build) only the .Net Core 1.1 is installed. The issue was that there were still tools dependencies in the project.json file that were depending on .Net Core 1.0, and running those tools were making the publish-iis fail.

Using the latest 1.1.0-preview4-final versions of

- Microsoft.AspNetCore.Razor.Tools
- Microsoft.AspNetCore.Server.IISIntegration.Tools
- Microsoft.DotNet.Watcher.Tools

fixes the issue and makes the all publish work correctly on the docker machine.

### CODE REVIEW

**Comment by Gimly** [comment]
Hello,

Is there something wrong with this pull request? Do you want me to fix something?

Regards

**Comment by RichiCoder1** [comment]
According to #684 this might be rendered redundant. AspNet peeps are probably in fire mode with VS RTM coming down the pipeline. /cc @natemcmaster

**Comment by SteveSandersonMS** [comment]
@Gimly Sorry this is taking a while to merge and for not commenting so far. Thanks for this contribution.

We're just working through transitioning everything in this repo to `csproj`-based tooling. Once that is done, some parts of this PR will still apply (the bits in the templates), and some parts will not (the bits in the samples). If we are retaining support for generating `project.json`-based projects, I'll then merge in the relevant parts of this PR. Hope that's OK!

**Comment by Gimly** [comment]
@SteveSandersonMS No problem! I was just wondering if there was something I could improve in the PR that was blocking your from merging. I completely understand that you're merging to the csproj-based tooling and that it has an impact.

**Comment by SteveSandersonMS** [comment]
Again, sorry this has taken a while to get to.

Now that dotnet's 1.0 `csproj` tooling has shipped, we'll shortly be pulling out the `project.json` vestiges from here. Obviously people who already have `project.json`-based projects can continue with them for as long as they want, but it doesn't really make sense for us to be shipping and maintaining tools to create *new* `project.json`-based projects. Newly-created projects should be `csproj`-based.

As such, the changes in this PR (which would have otherwise been valuable) will not be applicable any more. So to keep things tidy, I'll close this now.

Again, thanks for contributing this and for bearing with us while we make the transition to 1.0.0 tooling!

**Pull request closed without merging**
