### PR TITLE
Added docker support to sample projects

### PR DESCRIPTION
**Pull request by fbeltrao**
Hi,

I've added Docker support to the sample projects. There is a problem with webpack in the React MusicStore sample.

This is related to issue #768.

The file DockerSupport.md explains the problem and the solution.

Please let me know if you need more information.

### CODE REVIEW

**Comment by EduardTheThird** [comment]
Thank you for adding the docker samples! 

Will it be possible to add a example of using a Windows Container (microsoft/dotnet:nanoserver)?
I've been working on a Windows Container version. Currently it installs Node usings PowerShell and builds / publishes, however the site is not viewable once deployed in the container. 
It still needs to be optimized and moving to dotnet:nanoserver-runtime should help with the large size of this image.

```
FROM microsoft/dotnet:nanoserver

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 6.10.0
ENV NODE_SHA256 39c809fe02863963a4bb1eaa0daec59abcc92c0331447c3d3e06392a7f72b79c

RUN Invoke-WebRequest $('https://nodejs.org/dist/v{0}/node-v{0}-win-x64.zip' -f $env:NODE_VERSION) -OutFile 'node.zip' -UseBasicParsing ; \
		if ((Get-FileHash node.zip -Algorithm sha256).Hash -ne $env:NODE_SHA256) {exit 1} ; \
    Expand-Archive node.zip -DestinationPath C:\ ; \
    Rename-Item -Path $('C:\node-v{0}-win-x64' -f $env:NODE_VERSION) -NewName 'C:\nodejs' ; \
    New-Item $($env:APPDATA + '\npm') ; \
    $env:PATH = 'C:\nodejs;{0}\npm;{1}' -f $env:APPDATA, $env:PATH ; \
    Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\' -Name Path -Value $env:PATH ; \
    Remove-Item -Path node.zip

COPY . /app

WORKDIR /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "publish -o out"]

WORKDIR /app/out

ENV ASPNETCORE_URLS http://+:80
EXPOSE 80/tcp

ENTRYPOINT ["dotnet", "MusicStore.dll"]
CMD ["dotnet", "run", "--server.urls", "http://*:80"]
```

**Comment by SteveSandersonMS** [comment]
@fbeltrao Thanks very much for this contribution!

I'm not sure if you're familiar with the history, but we used to include `Dockerfile`s, but specifically removed them for consistency with other ASP.NET templates, and to reduce the concept count - this was in commit c9526dd4d238898e98f923382a067a04f3f10ba6. I don't think we'll want to re-add that as a default feature in the templates.

That said, the information you've provided is really high quality and will be valuable to anyone who does want to use Docker with these kinds of projects. People often do ask about it, so it would be great to have an official place to maintain this information.

Would you be OK with this information being added to [the repo's wiki](https://github.com/aspnet/JavaScriptServices/wiki)? We're only just getting started there, but the idea is to build up a repository of knowledge around related topics, and this would be a perfect fit.

**Comment by fbeltrao** [comment]
@SteveSandersonMS I was not aware of the Dockerfile consistency, sorry about that.
Of course you can add this information to the wiki page. Glad I can help.

Regards

**Comment by SteveSandersonMS** [comment]
Thanks! I'll mark this as closed then.

Would you be willing to provide the content to go in this wiki page? https://github.com/aspnet/JavaScriptServices/wiki/DockerSupport

I think the topics people will want to know about would be:

 * What Dockerfile is needed for local development
 * What Dockerfile is needed for publishing (if different)
 * Any specific VS2017 instructions

Does that sound right?

**Pull request closed without merging**
