### PR TITLE
Fix Docker for all templates.

### PR DESCRIPTION
**Pull request by EduardTheThird**
This fixes https://github.com/aspnet/JavaScriptServices/issues/669.

Thanks to @pysco68 for the tip!

### CODE REVIEW

**Comment by pysco68** [comment]
I think there's a better way to do so

**Comment by EduardTheThird** [comment]
Hi @pysco68,

That is pure genius, thank you for the tip. I can confirm by adding  the suggested env variable that docker now works. What changes would you recommend?

**Comment by pysco68** [comment]
Sorry, I was confusing something with the JS Service templates and my setup. 

No complaint at all! Great you put that together so quickly!

**Comment by SteveSandersonMS** [comment]
Thanks for submitting this!

I know this might be not what you personally want to hear, but I'm afraid we're going to remove the `Dockerfile`s from these templates. This is because it's not standard to have them in the ASP.NET Core templates (the regular File->New ones don't), and having them in by default causes issues (e.g., #694). People who do want to use Docker can of course continue to add the `Dockerfile` like they would to any other ASP.NET project and it will still work. It should not affect you personally in your current project since you've already created your project.

As such, I'll mark this as closed. If you'd be interested in adding a page to the [list of recipes wiki](https://github.com/aspnet/JavaScriptServices/wiki) about enabling Docker, that would be great though!

**Pull request closed without merging**
